using MySql.Data.MySqlClient;
using System;
using System.Data;
using System.Windows.Forms;

namespace PremiumLivingSystem
{
    public partial class UcCreateMaterialRequest : UserControl
    {
        public UcCreateMaterialRequest()
        {
            InitializeComponent();
        }

        // ================================================================
        // LOAD
        // ================================================================
        private void UcCreateMaterialRequest_Load(object sender, EventArgs e)
        {
            // Default urgency = Medium (matches DB default)
            cmbUrgency.SelectedIndex = 1;

            // Show today's date as the request date
            txtRequestDate.Text = DateTime.Now.ToString("yyyy-MM-dd HH:mm");

            // RequestID is auto-generated by DB trigger (MR-####), leave blank until saved
            txtRequestID.Text = "(auto on save)";

            LoadCurrentUser();
            LoadOrderItems();
            LoadMaterials();

            // React to material selection to show current stock
            cmbMaterial.SelectedIndexChanged += cmbMaterial_SelectedIndexChanged;
            nudQuantity.ValueChanged += nudQuantity_ValueChanged;
        }

        // ================================================================
        // DROPDOWN LOADING
        // ================================================================

        /// <summary>
        /// Load current user (Production Clerk) info from Staff table.
        /// RequestedBy is auto-filled from UserSession — read-only.
        /// </summary>
        private void LoadCurrentUser()
        {
            try
            {
                string staffId = UserSession.CurrentStaffId;
                if (string.IsNullOrEmpty(staffId))
                {
                    txtReqByID.Text = "";
                    txtReqName.Text = "";
                    txtReqPos.Text = "";
                    return;
                }

                string query = @"
                    SELECT s.StaffID, s.StaffName, j.Job_Title
                    FROM Staff s
                    JOIN Jobs j ON s.Job_ID = j.Job_ID
                    WHERE s.StaffID = @staffId";

                using (MySqlConnection conn = new MySqlConnection(Program.ConnectionString))
                {
                    MySqlCommand cmd = new MySqlCommand(query, conn);
                    cmd.Parameters.AddWithValue("@staffId", staffId);
                    conn.Open();
                    using (MySqlDataReader reader = cmd.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            txtReqByID.Text = reader["StaffID"].ToString();
                            txtReqName.Text = reader["StaffName"].ToString();
                            txtReqPos.Text = reader["Job_Title"].ToString();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("LoadCurrentUser failed: " + ex.Message);
            }
        }

        /// <summary>
        /// Load all OrderItems (only those whose parent Order is not Cancelled).
        /// Display: OrderItemID - OrderID - ProductName (Qty)
        /// </summary>
        private void LoadOrderItems()
        {
            string query = @"
                SELECT oi.OrderItemID,
                       CONCAT(oi.OrderItemID, '  |  Order: ', o.OrderID,
                              '  |  ', p.ProductName,
                              '  (Qty: ', oi.Quantity, ')') AS DisplayText
                FROM OrderItem oi
                JOIN `Order` o ON oi.OrderID = o.OrderID
                JOIN Product p ON oi.ProductID = p.ProductID
                WHERE o.Status <> 'Cancelled'
                ORDER BY oi.OrderItemID";

            try
            {
                DataTable dt = new DataTable();
                using (MySqlConnection conn = new MySqlConnection(Program.ConnectionString))
                {
                    MySqlCommand cmd = new MySqlCommand(query, conn);
                    MySqlDataAdapter da = new MySqlDataAdapter(cmd);
                    conn.Open();
                    da.Fill(dt);
                }

                cmbOrderItem.DataSource = dt;
                cmbOrderItem.DisplayMember = "DisplayText";
                cmbOrderItem.ValueMember = "OrderItemID";
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error loading Order Items: " + ex.Message);
            }
        }

        /// <summary>
        /// Load all Raw Materials for the material dropdown.
        /// Display: MaterialID - MaterialName [Unit]
        /// </summary>
        private void LoadMaterials()
        {
            string query = @"
                SELECT MaterialID,
                       MaterialName,
                       Unit,
                       StockQty,
                       CONCAT(MaterialID, '  |  ', MaterialName, '  [', Unit, ']') AS DisplayText
                FROM RawMaterial
                ORDER BY MaterialID";

            try
            {
                DataTable dt = new DataTable();
                using (MySqlConnection conn = new MySqlConnection(Program.ConnectionString))
                {
                    MySqlCommand cmd = new MySqlCommand(query, conn);
                    MySqlDataAdapter da = new MySqlDataAdapter(cmd);
                    conn.Open();
                    da.Fill(dt);
                }

                cmbMaterial.DataSource = dt;
                cmbMaterial.DisplayMember = "DisplayText";
                cmbMaterial.ValueMember = "MaterialID";

                // Show stock of first material
                UpdateStockInfo();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error loading Raw Materials: " + ex.Message);
            }
        }

        /// <summary>
        /// When user selects a material, display its current stock to help them
        /// decide the urgency and required date.
        /// </summary>
        private void cmbMaterial_SelectedIndexChanged(object sender, EventArgs e)
        {
            UpdateStockInfo();
        }

        private void UpdateStockInfo()
        {
            try
            {
                if (cmbMaterial.SelectedItem == null)
                {
                    lblStockInfo.Text = "";
                    return;
                }

                DataRowView row = cmbMaterial.SelectedItem as DataRowView;
                if (row == null) return;

                object stockObj = row["StockQty"];
                string unit = row["Unit"].ToString();
                decimal stock = 0m;
                if (stockObj != null && stockObj != DBNull.Value)
                    stock = Convert.ToDecimal(stockObj);

                // Color-code: green if enough, amber/red if low
                decimal requestedQty = nudQuantity.Value;
                if (stock >= requestedQty)
                {
                    lblStockInfo.ForeColor = System.Drawing.Color.FromArgb(60, 110, 60);
                    lblStockInfo.Text = $"In stock: {stock} {unit}";
                }
                else
                {
                    lblStockInfo.ForeColor = System.Drawing.Color.FromArgb(180, 70, 30);
                    lblStockInfo.Text = $"Low stock: {stock} {unit}";
                }
            }
            catch
            {
                lblStockInfo.Text = "";
            }
        }

        // Also update stock hint when quantity changes
        private void nudQuantity_ValueChanged(object sender, EventArgs e)
        {
            UpdateStockInfo();
        }

        // ================================================================
        // SUBMIT
        // ================================================================

        private void btnSubmit_Click(object sender, EventArgs e)
        {
            // 1. Validate inputs
            if (cmbOrderItem.SelectedValue == null)
            {
                MessageBox.Show("Please select an Order Item.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            if (cmbMaterial.SelectedValue == null)
            {
                MessageBox.Show("Please select a Raw Material.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            if (nudQuantity.Value <= 0)
            {
                MessageBox.Show("Quantity must be greater than 0.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            if (cmbUrgency.SelectedIndex < 0)
            {
                MessageBox.Show("Please select an urgency level.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            if (dtpRequiredDate.Value.Date < DateTime.Today)
            {
                MessageBox.Show("Required Delivery Date cannot be in the past.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // 2. Confirm (T3 style: YesNo dialog)
            var confirm = MessageBox.Show(
                "Are you sure you want to submit this Raw Material Request?",
                "Confirm Submit",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Question);
            if (confirm != DialogResult.Yes) return;

            // 3. Collect values
            string orderItemID = cmbOrderItem.SelectedValue.ToString();
            string materialID = cmbMaterial.SelectedValue.ToString();
            decimal quantity = nudQuantity.Value;
            string urgency = cmbUrgency.SelectedItem.ToString();
            string requiredDate = dtpRequiredDate.Value.ToString("yyyy-MM-dd");
            string requestedBy = txtReqByID.Text.Trim();
            string remarks = txtRemarks.Text.Trim();

            // 4. INSERT (RequestID is auto-generated by DB trigger → MR-####)
            string insertQuery = @"
                INSERT INTO MaterialRequest
                    (OrderItemID, MaterialID, Quantity, UrgencyLevel,
                     RequiredDeliveryDate, RequestedBy, Status, Remarks)
                VALUES
                    (@oi, @mat, @qty, @urg,
                     @rdd, @rb, 'Requested', @rem)";

            try
            {
                using (MySqlConnection conn = new MySqlConnection(Program.ConnectionString))
                {
                    MySqlCommand cmd = new MySqlCommand(insertQuery, conn);
                    cmd.Parameters.AddWithValue("@oi", orderItemID);
                    cmd.Parameters.AddWithValue("@mat", materialID);
                    cmd.Parameters.AddWithValue("@qty", quantity);
                    cmd.Parameters.AddWithValue("@urg", urgency);
                    cmd.Parameters.AddWithValue("@rdd", requiredDate);
                    cmd.Parameters.AddWithValue("@rb", requestedBy);
                    cmd.Parameters.AddWithValue("@rem", string.IsNullOrEmpty(remarks) ? (object)DBNull.Value : remarks);

                    conn.Open();
                    int rowsAffected = cmd.ExecuteNonQuery();

                    if (rowsAffected > 0)
                    {
                        // Retrieve the auto-generated RequestID (trigger format: MR-####)
                        string getIdQuery = @"
                            SELECT RequestID FROM MaterialRequest
                            WHERE RequestedBy = @rb
                            ORDER BY RequestID DESC LIMIT 1";
                        MySqlCommand cmdGetId = new MySqlCommand(getIdQuery, conn);
                        cmdGetId.Parameters.AddWithValue("@rb", requestedBy);
                        object result = cmdGetId.ExecuteScalar();
                        string newId = (result != null) ? result.ToString() : "(unknown)";

                        MessageBox.Show(
                            $"Raw Material Request submitted successfully.\nRequest ID: {newId}",
                            "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);

                        // Display the generated ID on the form
                        txtRequestID.Text = newId;
                        txtStatus.Text = "Requested";

                        // Reset form for next entry (T3 style: clear after success)
                        ClearForm();
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error inserting record: " + ex.Message,
                    "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        // ================================================================
        // CLEAR
        // ================================================================

        private void btnClear_Click(object sender, EventArgs e)
        {
            ClearForm();
        }

        private void ClearForm()
        {
            // Reset dropdowns
            if (cmbOrderItem.Items.Count > 0) cmbOrderItem.SelectedIndex = 0;
            if (cmbMaterial.Items.Count > 0) cmbMaterial.SelectedIndex = 0;

            // Reset quantity
            nudQuantity.Value = 1;

            // Reset urgency to Medium
            cmbUrgency.SelectedIndex = 1;

            // Reset required date to today + 3 days
            dtpRequiredDate.Value = DateTime.Today.AddDays(3);

            // Clear remarks
            txtRemarks.Clear();

            // Reset ID placeholder
            txtRequestID.Text = "(auto on save)";
            txtStatus.Text = "Requested";

            // Refresh request date
            txtRequestDate.Text = DateTime.Now.ToString("yyyy-MM-dd HH:mm");
        }
    }
}
